# Generated by Django 5.0.8 on 2024-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_account_type_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Admin', 'Admin')], default='Student', max_length=100),
        ),
    ]
