# Generated by Django 5.0.8 on 2024-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_course_type_normal_type'),
        ('users', '0003_alter_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_orders',
            field=models.ManyToManyField(blank=True, to='orders.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='normal_orders',
            field=models.ManyToManyField(blank=True, to='orders.normal'),
        ),
    ]
