# Generated by Django 5.0.1 on 2024-09-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_course_orders_profile_normal_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='09887673783', max_length=100),
            preserve_default=False,
        ),
    ]
