# Generated by Django 5.0.8 on 2024-09-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_normal_client_normal_completed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('S', 'Successful'), ('C', 'Cancelled'), ('F', 'Failed')], default='S', max_length=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.normal')),
            ],
        ),
    ]
