# Generated by Django 5.0.8 on 2024-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normal',
            name='is_progressive',
        ),
        migrations.AlterField(
            model_name='normal',
            name='attach_plagiarism_report',
            field=models.CharField(default='0', help_text='value of 1 is yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='normal',
            name='citation',
            field=models.CharField(blank=True, choices=[('Harvard', 'Harvard'), ('Chicago', 'Chicago'), ('Turabian', 'Turabian'), ('Other', 'Other')], max_length=300),
        ),
        migrations.AlterField(
            model_name='normal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normal',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normal',
            name='sources',
            field=models.CharField(choices=[('0', '0 Sources'), ('0.035', '2 Sources'), ('0.045', '0 Sources'), ('0.067', '8 Sources'), ('0.9', '10 Sources'), ('1.1', '15 Sources')], max_length=100),
        ),
    ]
