# Generated by Django 5.0.8 on 2024-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_normal_is_progressive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='academic_level_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='assignment_size_pages_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='assignment_type_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='citation_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='deadline_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='language_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='other_citation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='slides_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='sources_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='spacing_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='normal',
            name='subject_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normal',
            name='sources',
            field=models.CharField(choices=[('0', '0 Sources'), ('0.035', '2 Sources'), ('0.045', '5 Sources'), ('0.067', '8 Sources'), ('0.9', '10 Sources'), ('1.1', '15 Sources')], max_length=100),
        ),
    ]
