# Generated by Django 5.0.8 on 2024-09-09 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_normal_academic_level_text_and_more'),
        ('users', '0002_remove_user_name_user_account_type_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_normal_order', to='users.profile'),
        ),
        migrations.AddField(
            model_name='normal',
            name='completed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='normal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normal',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normal',
            name='is_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normal',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
