# Generated by Django 5.0.8 on 2024-09-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_normal_client_normal_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normal',
            name='uploads',
        ),
        migrations.CreateModel(
            name='NormalOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(blank=True, null=True, upload_to='')),
                ('normal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.normal')),
            ],
        ),
    ]
