# Generated by Django 5.0.8 on 2024-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_normal_uploads_normalorderfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normal',
            options={'get_latest_by': 'order_date'},
        ),
        migrations.AddField(
            model_name='normal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
