# Generated by Django 5.0.8 on 2024-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_normal_options_normal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='slug',
            field=models.SlugField(default='testing detaiul pages', max_length=100),
            preserve_default=False,
        ),
    ]
