# Generated by Django 5.0.8 on 2024-09-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_normal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalorderfile',
            name='normal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='orders.normal'),
        ),
    ]
