# Generated by Django 5.0.8 on 2024-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_normalorderfile_normal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
