# Generated by Django 5.0.8 on 2024-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_normal_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='revision_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalorderfile',
            name='uploads',
            field=models.FileField(blank=True, null=True, upload_to='norma_order/'),
        ),
    ]
