# Generated by Django 5.0.8 on 2024-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_normal_revision_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
