# Generated by Django 5.0.8 on 2024-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_normal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
