# Generated by Django 5.0.8 on 2024-09-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_normal_is_active'),
        ('users', '0002_remove_user_name_user_account_type_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalOrderCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='normal_order/completed/files/')),
                ('comment', models.TextField(blank=True)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('normal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_completed_order', to='orders.normal')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='writer_normal_order', to='users.profile')),
            ],
        ),
    ]
