# Generated by Django 5.0.8 on 2024-09-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_normalordercompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normalordercompleted',
            options={'get_latest_by': 'completed_date', 'verbose_name': 'Completed Order', 'verbose_name_plural': 'Completed Orders'},
        ),
    ]
