# Generated by Django 5.0.8 on 2024-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_normalordercompleted_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalordercompleted',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
