# Generated by Django 5.0.8 on 2024-09-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_normalordercompleted_approved'),
        ('users', '0003_alter_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(choices=[('0.9', 'High School'), ('1.1', 'College'), ('1.5', 'Undergraduate'), ('1.9', 'Masters'), ('2.1', 'Phd')], max_length=100)),
                ('academic_level_text', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('subject', models.CharField(choices=[('1', 'General'), ('51', 'Accounting'), ('50', 'Archaeology'), ('2', 'Architecture'), ('3', 'Arts'), ('4', 'Astronomy'), ('5', 'Biology'), ('6', 'Business'), ('7', 'Chemistry'), ('8', 'Childcare'), ('9', 'Computers'), ('10', 'Counseling'), ('11', 'Criminology'), ('12', 'Economics'), ('13', 'Education'), ('14', 'Engineering'), ('53', 'English'), ('15', 'Environmental-Studies'), ('55', 'Eric B Mueller'), ('54', 'Esports'), ('16', 'Ethics'), ('17', 'Ethnic-Studies'), ('18', 'Finance'), ('19', 'Food-Nutrition'), ('1', 'General'), ('20', 'Geography'), ('21', 'Healthcare'), ('22', 'History'), ('48', 'Human Resource Management'), ('23', 'Law'), ('24', 'Linguistics'), ('25', 'Literature'), ('26', 'Management'), ('27', 'Mathematics'), ('56', 'Matthew'), ('28', 'Medicine'), ('29', 'Music'), ('30', 'Nursing'), ('47', 'Other'), ('31', 'Philosophy'), ('32', 'Physical-Education'), ('33', 'Physics'), ('34', 'Political-Science'), ('35', 'Programming'), ('36', 'Psychology'), ('52', 'Public Speaking'), ('37', 'Religion'), ('38', 'Sociology'), ('39', 'Statistics'), ('49', 'System Design')], max_length=200)),
                ('subject_text', models.CharField(max_length=1000)),
                ('number_of_weeks_or_assignments', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('course_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('course_url', models.URLField(max_length=3000)),
                ('student_username', models.CharField(max_length=1000)),
                ('student_course_login_password', models.CharField(help_text='This is case sensitive', max_length=3000)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_assigned', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_course_order', to='users.profile')),
            ],
            options={
                'get_latest_by': 'order_date',
            },
        ),
    ]
