# Generated by Django 5.0.8 on 2024-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='normal',
            name='type',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
