# Generated by Django 5.0.1 on 2024-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_course_type_normal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=15),
        ),
    ]
